/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_darrenyuan_nativefeedback_MainActivity */

#ifndef _Included_com_darrenyuan_nativefeedback_MainActivity
#define _Included_com_darrenyuan_nativefeedback_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_darrenyuan_nativefeedback_MainActivity
 * Method:    nativeHelloWorld
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_darrenyuan_nativefeedback_MainActivity_nativeHelloWorld
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
