/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_darrenyuan_nativefeedback_JniTest */

#ifndef _Included_com_darrenyuan_nativefeedback_JniTest
#define _Included_com_darrenyuan_nativefeedback_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_darrenyuan_nativefeedback_JniTest
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_darrenyuan_nativefeedback_JniTest_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
